### ISSUE TITLE
帖子在控制台显示已发布，但实际并未成功发布

### ISSUE THREAD

**Issue by GrassBlock1** [laoxong/Fediverse-Bridge#1]
咱填了配置运行后，测试了下频道发帖。
虽然终端显示“发布帖子成功”，但是我刷新了好几次，misskey端也没有对应note。

相关日志如下：
https://paste.o3o.studio/?e0f9ed210ba9448e#8p6jADmRp3vYEDmJtSC8ruKRWzkiGmgxNQgA72N6D11j

配置：
https://paste.o3o.studio/?8baba415d0784dc6#CWcBHBu11YoxggM73FhCSjJPWm4oWBkv6GkoZfrQQJdA

（（（（（

**Comment by laoxong** [comment]
配置文件中第一行没有`cw`

**Comment by laoxong** [comment]
看起来像是API请求失败，您是在本地跑的？

**Comment by GrassBlock1** [comment]
> 看起来像是API请求失败，您是在本地跑的？

是这样的...

**Comment by GrassBlock1** [comment]
> 配置文档中第一行没有`cw`

？啥意思

**Comment by laoxong** [comment]
> > 看起来像是API请求失败，您是在本地跑的？
> 
> 是这样的...

那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP）
请自行修改代码或使用TUN模式等基于三层网络的代理

**Comment by GrassBlock1** [comment]
> > > 看起来像是API请求失败，您是在本地跑的？
> > 
> > 
> > 是这样的...
> 
> 那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP） 请自行修改代码或使用TUN模式等基于三层网络的代理

行 我看看
好像v2raya那透明代理炸了

**Comment by GrassBlock1** [comment]
> > > 看起来像是API请求失败，您是在本地跑的？
> > 
> > 
> > 是这样的...
> 
> 那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP） 请自行修改代码或使用TUN模式等基于三层网络的代理

我看了一下v2raya那边的日志 m.moec.top 是走了代理的（我开了全局透明代理），但还是发不出去
```
2022/12/30 14:00:06.937 [I] [io.go:429]  127.0.0.1:52312 accepted //m.moec.top:443 [proxy]
2022/12/30 14:00:16.015 [I] [io.go:429]  192.168.0.29:35866 accepted udp:144.76.76.107:123 [proxy]
2022/12/30 14:00:16.646 [I] [io.go:429]  127.0.0.1:47618 accepted //api.telegram.org:443 [proxy]
2022/12/30 14:00:26.264 [I] [io.go:429]  192.168.0.29:48595 accepted udp:193.182.111.143:123 [proxy]
```

**Comment by laoxong** [comment]
> > > > 看起来像是API请求失败，您是在本地跑的？
> > > 
> > > 
> > > 是这样的...
> > 
> > 
> > 那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP） 请自行修改代码或使用TUN模式等基于三层网络的代理
> 
> 我看了一下v2raya那边的日志 m.moec.top 是走了代理的（我开了全局透明代理），但还是发不出去
> 
> ```
> 2022/12/30 14:00:06.937 [I] [io.go:429]  127.0.0.1:52312 accepted //m.moec.top:443 [proxy]
> 2022/12/30 14:00:16.015 [I] [io.go:429]  192.168.0.29:35866 accepted udp:144.76.76.107:123 [proxy]
> 2022/12/30 14:00:16.646 [I] [io.go:429]  127.0.0.1:47618 accepted //api.telegram.org:443 [proxy]
> 2022/12/30 14:00:26.264 [I] [io.go:429]  192.168.0.29:48595 accepted udp:193.182.111.143:123 [proxy]
> ```

请git pull后重新运行
我在 https://github.com/laoxong/Fediverse-Bridge/commit/acf394c96cb8cbfc00f73bee75a858de19c14d7b 优化了log记录

**Comment by GrassBlock1** [comment]
> > > > > 看起来像是API请求失败，您是在本地跑的？
> > > > 
> > > > 
> > > > 是这样的...
> > > 
> > > 
> > > 那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP） 请自行修改代码或使用TUN模式等基于三层网络的代理
> > 
> > 
> > 我看了一下v2raya那边的日志 m.moec.top 是走了代理的（我开了全局透明代理），但还是发不出去
> > ```
> > 2022/12/30 14:00:06.937 [I] [io.go:429]  127.0.0.1:52312 accepted //m.moec.top:443 [proxy]
> > 2022/12/30 14:00:16.015 [I] [io.go:429]  192.168.0.29:35866 accepted udp:144.76.76.107:123 [proxy]
> > 2022/12/30 14:00:16.646 [I] [io.go:429]  127.0.0.1:47618 accepted //api.telegram.org:443 [proxy]
> > 2022/12/30 14:00:26.264 [I] [io.go:429]  192.168.0.29:48595 accepted udp:193.182.111.143:123 [proxy]
> > ```
> 
> 请git pull后重新运行 我在 [acf394c](https://github.com/laoxong/Fediverse-Bridge/commit/acf394c96cb8cbfc00f73bee75a858de19c14d7b) 优化了log记录

我重新运行了一次...log如下：
https://paste.o3o.studio/?b446f23df2be7b0f#A7bxqnQbXcYtFgBCL7vzrrAtD3nqx3aiouL5grnAXVen
大概是token权限问题？依据权限最小化原则，我应该创建一个具备什么权限的token？
另附现有token的权限：
![图片](https://user-images.githubusercontent.com/46253950/210057717-af6aa41a-9d2f-44f6-a7db-4dddf49cf75c.png)

**Comment by laoxong** [comment]
> > > > > > 看起来像是API请求失败，您是在本地跑的？
> > > > > 
> > > > > 
> > > > > 是这样的...
> > > > 
> > > > 
> > > > 那应该是requests没走代理导致无法连接到m.moec.top（我禁止了国内IP） 请自行修改代码或使用TUN模式等基于三层网络的代理
> > > 
> > > 
> > > 我看了一下v2raya那边的日志 m.moec.top 是走了代理的（我开了全局透明代理），但还是发不出去
> > > ```
> > > 2022/12/30 14:00:06.937 [I] [io.go:429]  127.0.0.1:52312 accepted //m.moec.top:443 [proxy]
> > > 2022/12/30 14:00:16.015 [I] [io.go:429]  192.168.0.29:35866 accepted udp:144.76.76.107:123 [proxy]
> > > 2022/12/30 14:00:16.646 [I] [io.go:429]  127.0.0.1:47618 accepted //api.telegram.org:443 [proxy]
> > > 2022/12/30 14:00:26.264 [I] [io.go:429]  192.168.0.29:48595 accepted udp:193.182.111.143:123 [proxy]
> > > ```
> > 
> > 
> > 请git pull后重新运行 我在 [acf394c](https://github.com/laoxong/Fediverse-Bridge/commit/acf394c96cb8cbfc00f73bee75a858de19c14d7b) 优化了log记录
> 
> 我重新运行了一次...log如下： https://paste.o3o.studio/?b446f23df2be7b0f#A7bxqnQbXcYtFgBCL7vzrrAtD3nqx3aiouL5grnAXVen 大概是token权限问题？依据权限最小化原则，我应该创建一个具备什么权限的token？ 另附现有token的权限： ![图片](https://user-images.githubusercontent.com/46253950/210057717-af6aa41a-9d2f-44f6-a7db-4dddf49cf75c.png)

![Screenshot_20221230-194707_Pixel 启动器](https://user-images.githubusercontent.com/31268830/210067161-f210322f-627d-4779-8328-922064fa2b19.png)
这些权限就够了，
重新申请个API密钥呢？

**Comment by GrassBlock1** [comment]
https://paste.o3o.studio/?3cda7ea0fe8ec72b#8zmKWY1J6zECimQNqj6qaE4NMShc7QiLVKseidKen275
这次可以了，~~但是好像其它bot发的链接转成markdown链接以后炸了~~
